INSERT INTO public.categories (id, image_url, is_feature, name) VALUES (1, 'https://example.com/images/eletronicos.jpg', true, 'Eletrônicos');
INSERT INTO public.categories (id, image_url, is_feature, name) VALUES (2, 'https://example.com/images/moda_feminina.jpg', true, 'Moda Feminina');
INSERT INTO public.categories (id, image_url, is_feature, name) VALUES (3, 'https://example.com/images/casa_e_cozinha.jpg', false, 'Casa e Cozinha');
INSERT INTO public.categories (id, image_url, is_feature, name) VALUES (4, 'https://example.com/images/esportes.jpg', true, 'Esportes e Lazer');
INSERT INTO public.categories (id, image_url, is_feature, name) VALUES (5, 'https://example.com/images/livros.jpg', false, 'Livros e Papelaria');
INSERT INTO public.categories (id, image_url, is_feature, name) VALUES (6, 'https://example.com/images/informatica.jpg', true, 'Informática');
INSERT INTO public.categories (id, image_url, is_feature, name) VALUES (7, 'https://example.com/images/beleza.jpg', false, 'Beleza e Perfumaria');
INSERT INTO public.categories (id, image_url, is_feature, name) VALUES (8, 'https://example.com/images/brinquedos.jpg', false, 'Brinquedos e Jogos');
INSERT INTO public.categories (id, image_url, is_feature, name) VALUES (9, 'https://example.com/images/automotivo.jpg', false, 'Automotivo');
INSERT INTO public.categories (id, image_url, is_feature, name) VALUES (10, 'https://example.com/images/moda_masculina.jpg', true, 'Moda Masculina');
INSERT INTO public.categories (id, image_url, is_feature, name) VALUES (11, 'https://example.com/images/celulares.jpg', true, 'Celulares e Smartphones');
INSERT INTO public.categories (id, image_url, is_feature, name) VALUES (12, 'https://example.com/images/ferramentas.jpg', false, 'Ferramentas');
INSERT INTO public.categories (id, image_url, is_feature, name) VALUES (13, 'https://example.com/images/bebes.jpg', false, 'Produtos para Bebês');
INSERT INTO public.categories (id, image_url, is_feature, name) VALUES (14, 'https://example.com/images/alimentos.jpg', false, 'Alimentos e Bebidas');
INSERT INTO public.categories (id, image_url, is_feature, name) VALUES (15, 'https://example.com/images/pet_shop.jpg', true, 'Pet Shop');
INSERT INTO public.categories (id, image_url, is_feature, name) VALUES (16, 'https://example.com/images/games.jpg', true, 'Games e Consoles');
INSERT INTO public.categories (id, image_url, is_feature, name) VALUES (17, 'https://example.com/images/moveis.jpg', false, 'Móveis e Decoração');
INSERT INTO public.categories (id, image_url, is_feature, name) VALUES (18, 'https://example.com/images/audio_tv.jpg', false, 'Áudio, TV e Vídeo');
INSERT INTO public.categories (id, image_url, is_feature, name) VALUES (19, 'https://example.com/images/saude.jpg', false, 'Saúde e Bem-estar');
INSERT INTO public.categories (id, image_url, is_feature, name) VALUES (20, 'https://example.com/images/calcados.jpg', true, 'Calçados');
INSERT INTO public.categories (id, image_url, is_feature, name) VALUES (21, 'https://example.com/images/jardim.jpg', false, 'Jardim e Piscina');
INSERT INTO public.categories (id, image_url, is_feature, name) VALUES (22, 'https://example.com/images/eletrodomesticos.jpg', true, 'Eletrodomésticos');
INSERT INTO public.categories (id, image_url, is_feature, name) VALUES (23, 'https://example.com/images/viagem.jpg', false, 'Malas e Acessórios de Viagem');
INSERT INTO public.categories (id, image_url, is_feature, name) VALUES (24, 'https://example.com/images/musica.jpg', false, 'Instrumentos Musicais');
INSERT INTO public.categories (id, image_url, is_feature, name) VALUES (25, 'https://example.com/images/relogios.jpg', true, 'Relógios');
INSERT INTO public.categories (id, image_url, is_feature, name) VALUES (26, 'https://example.com/images/moda_infantil.jpg', false, 'Moda Infantil');
INSERT INTO public.categories (id, image_url, is_feature, name) VALUES (27, 'https://example.com/images/artesanato.jpg', false, 'Arte e Artesanato');
INSERT INTO public.categories (id, image_url, is_feature, name) VALUES (28, 'https://example.com/images/cama_mesa_banho.jpg', false, 'Cama, Mesa e Banho');
INSERT INTO public.categories (id, image_url, is_feature, name) VALUES (29, 'https://example.com/images/suplementos.jpg', true, 'Suplementos Alimentares');
INSERT INTO public.categories (id, image_url, is_feature, name) VALUES (30, 'https://example.com/images/eletroportateis.jpg', false, 'Eletroportáteis');
INSERT INTO public.categories (id, image_url, is_feature, name) VALUES (31, 'https://example.com/images/perfumes_importados.jpg', true, 'Perfumes Importados');
INSERT INTO public.categories (id, image_url, is_feature, name) VALUES (32, 'https://example.com/images/cameras.jpg', false, 'Câmeras e Drones');
INSERT INTO public.categories (id, image_url, is_feature, name) VALUES (33, 'https://example.com/images/smart_home.jpg', true, 'Casa Inteligente');
INSERT INTO public.categories (id, image_url, is_feature, name) VALUES (34, 'https://example.com/images/vinhos.jpg', false, 'Vinhos');
INSERT INTO public.categories (id, image_url, is_feature, name) VALUES (35, 'https://example.com/images/material_escritorio.jpg', false, 'Material de Escritório');
INSERT INTO public.categories (id, image_url, is_feature, name) VALUES (36, 'https://example.com/images/hqs.jpg', false, 'Histórias em Quadrinhos');
INSERT INTO public.categories (id, image_url, is_feature, name) VALUES (37, 'https://example.com/images/fitness.jpg', true, 'Artigos para Fitness');
INSERT INTO public.categories (id, image_url, is_feature, name) VALUES (38, 'https://example.com/images/oculos_sol.jpg', false, 'Óculos de Sol');
INSERT INTO public.categories (id, image_url, is_feature, name) VALUES (39, 'https://example.com/images/acessorios_informatica.jpg', false, 'Acessórios de Informática');
INSERT INTO public.categories (id, image_url, is_feature, name) VALUES (40, 'https://example.com/images/pneus.jpg', false, 'Pneus e Rodas');
INSERT INTO public.categories (id, image_url, is_feature, name) VALUES (41, 'https://example.com/images/mochilas.jpg', false, 'Mochilas');
INSERT INTO public.categories (id, image_url, is_feature, name) VALUES (42, 'https://example.com/images/beleza_profissional.jpg', false, 'Produtos de Beleza Profissional');
INSERT INTO public.categories (id, image_url, is_feature, name) VALUES (43, 'https://example.com/images/chocolates.jpg', false, 'Chocolates e Doces');
INSERT INTO public.categories (id, image_url, is_feature, name) VALUES (44, 'https://example.com/images/papelaria_criativa.jpg', false, 'Papelaria Criativa');
INSERT INTO public.categories (id, image_url, is_feature, name) VALUES (45, 'https://example.com/images/roupas_intimas.jpg', false, 'Roupas Íntimas');
INSERT INTO public.categories (id, image_url, is_feature, name) VALUES (46, 'https://example.com/images/camping.jpg', true, 'Camping e Aventura');
INSERT INTO public.categories (id, image_url, is_feature, name) VALUES (47, 'https://example.com/images/limpeza.jpg', false, 'Produtos de Limpeza');
INSERT INTO public.categories (id, image_url, is_feature, name) VALUES (48, 'https://example.com/images/antiguidades.jpg', false, 'Antiguidades e Colecionáveis');
INSERT INTO public.categories (id, image_url, is_feature, name) VALUES (49, 'https://example.com/images/filmes_series.jpg', false, 'Filmes e Séries');
INSERT INTO public.categories (id, image_url, is_feature, name) VALUES (50, 'https://example.com/images/cueca.jpg', true, 'Moda Intima Masculina');